### ISSUE TITLE
Roadmap for version 0.3

### ISSUE THREAD

**Issue by byaka** [byaka/wartts#1]
- [x] Map rendering and general layers _(background with effects, static markers, dinamic markers, player, additional info (path, windrose, etc.))_
- [x] Calculate heading of objects and correctly rotate markers on map
- [ ] Track objects
- [x] Map's zoom, moving (dragging by mouse) and rotating
- [ ] Map's zoom "at pointer" and "at player"
- [x] Map's zoom "at objects" (all objects must be in screen, but nothing more) and auto pan
- [x] Get, processing and render general indicators for aircraft
- [x] Calculate distance from player to every object
